{% set version = "0.5.2" %}

package:
  name: pymatbridge
  version: {{ version }}

source:
  fn: pymatbridge-{{ version }}.tar.gz
  url: https://github.com/arokem/python-matlab-bridge/archive/{{ version }}.tar.gz
  sha256: 01592cfbef74fa21c9bc61db7f8d09ff05f1806f8c986b2649a7b6a2a4e3b15c

build:
  noarch: python
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pyzmq
    - numpy
  run:
    - python
    - pyzmq
    - numpy

test:
  imports:
    - pymatbridge

about:
  home: https://github.com/arokem/python-matlab-bridge
  license: BSD 2-Clause
  summary: 'Python-MATLAB(R) Bridge and IPython.'

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
