{% set version = "0.5.2" %}

package:
  name: pymatbridge
  version: {{ version }}

source:
  url: https://github.com/arokem/python-matlab-bridge/archive/{{ version }}.tar.gz
  sha256: 01592cfbef74fa21c9bc61db7f8d09ff05f1806f8c986b2649a7b6a2a4e3b15c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - pyzmq
    - numpy
  run:
    - python >={{ python_min }}
    - pyzmq
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymatbridge

about:
  home: https://github.com/arokem/python-matlab-bridge
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Python-MATLAB(R) Bridge and IPython'

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
