{% set version = "0.5.2" %}

package:
  name: pymatbridge
  version: {{ version }}

source:
  url: https://github.com/arokem/python-matlab-bridge/archive/{{ version }}.tar.gz
  sha256: 01592cfbef74fa21c9bc61db7f8d09ff05f1806f8c986b2649a7b6a2a4e3b15c

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pyzmq
    - numpy
  run:
    - python
    - pyzmq
    - numpy

test:
  imports:
    - pymatbridge

about:
  home: https://github.com/arokem/python-matlab-bridge
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python-MATLAB(R) Bridge and IPython'

extra:
  recipe-maintainers:
    - arokem
    - ocefpaf
