travis:
  secure:
    BINSTAR_TOKEN: uAX7vHaB4Ac9RYLgxlmCLCVX27gzLhC1hFA7vLDgh7UzWjCywinR+70Zk+9N5y2Y39JpVF0msj2GViTR9W8z5q7l4kQRRe750LpUM9j9MRZI6w7pgILpb9plueTVYUaD+0WxyJJQ6W4LEn4JG3V1oFRZTPCpJ6R0CXJH8j3LLWwiGPEE9b1EiZXmxBSninygZ9tUTZZX/9yF2IRvzrvIEx2k24mIOBa68wtIRSz081KRhrLYsmcfGSmPDFuCfgpUypbEYek4I00p0A89Q7YTW5pwHXf45NLQ1PMMPgyjU4f7ARlG7DHV82JCpHdr3UlkSCnFnpE5ClmHJH5ZKEsRBxc1pAyeOXIRB6+dCtOQAeQd1Fli3GWe3nuuIhxj2+OkMBSZFeqf4My1j4h4C28VzsqDggebo27P9Vk1eZ5gK/NQR4XESOnuJFSD/ILqA6FgkZG1hhdZV9Ocm4xkok5I4o23BITtQOGTZPg5FQqqgxLjFSir4QytKAnVEvjLibr9+PGx6WKJl+/GqCN1q1Bt4b//vtjiiz0Iw+X3ZgswasprvU4t2vM/v0GLXTPs2VkvAZPaGu7MtBQeDLwYtrd/TOWLOrXSmONBP7qWQwbIyRACWp3NbiRxLxXca/6MWFn9cesbvt9FNTCKzGtQH1pSxRfit7OUHVoOv0ypmUo8cSY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
